# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '2.2.300'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: NodeTool@0 
  inputs:
    versionSpec: '10.x'

- script: yarn install
  displayName: 'yarn install'

- script: yarn run build
  displayName: 'yarn build'

- script: yarn test
  displayName: 'yarn test'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '$(System.DefaultWorkingDirectory)/junit.xml'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'cobertura'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/test/coverage-jest/cobertura-coverage.xml'

- script: dotnet clean
  displayName: 'dotnet clean'

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    zipAfterPublish: True

- task: PublishBuildArtifacts@1
