# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '2.2.300'

- script: yarn install
  displayName: 'yarn install'

- script: yarn test
  displayName: 'yarn test'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '$(System.DefaultWorkingDirectory)/testresults/*.xml'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'cobertura'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/testresults/coverage/*.xml'

- script: dotnet clean
  displayName: 'dotnet clean'

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    arguments: '--configuration $(BuildConfiguration)'
    zipAfterPublish: True

- task: AzureRmWebAppDeployment@4
  displayName: 'Deploy Azure App Service'
  inputs:
    azureSubscription: '$(DeploymentServiceConnectionName)'
    appType: webApp
    WebAppName: '$(DeploymentWebAppName)'
